package org.booktower.config

import gg.jte.ContentType
import gg.jte.TemplateEngine
import gg.jte.output.StringOutput
import gg.jte.resolve.DirectoryCodeResolver
import java.nio.file.Path

class TemplateRenderer {
    companion object {
        private val logger = org.slf4j.LoggerFactory.getLogger("booktower.TemplateRenderer")
    }

    private val engine: TemplateEngine by lazy {
        // Decide between dynamic (live-reload) and precompiled (production) template engines.
        //
        // Dynamic engine: reads .kte files from src/main/jte/ at runtime, recompiles on change.
        //   Used when: BOOKTOWER_ENV != "production" AND source tree exists AND NOT running from a fat JAR.
        //   Output goes to target/jte-dynamic/ (separate from Maven's target/generated-sources/jte/).
        //
        // Precompiled engine: uses classes generated by jte-maven-plugin at build time.
        //   Used when: running from fat JAR, native binary, Docker, or BOOKTOWER_ENV=production.
        //
        // Detection: if the classloader's code source is a JAR file, we're in a fat JAR
        // and the dynamic engine would conflict with the precompiled classes on the classpath.
        val isDev = System.getenv("BOOKTOWER_ENV")?.lowercase() != "production"
        val sourceDir = Path.of("src/main/jte")
        val isJar =
            javaClass.protectionDomain
                ?.codeSource
                ?.location
                ?.path
                ?.endsWith(".jar") == true
        // GraalVM native image: System.getProperty("org.graalvm.nativeimage.imagecode") is set
        val isNativeImage = System.getProperty("org.graalvm.nativeimage.imagecode") != null

        if (isDev && sourceDir.toFile().isDirectory && !isJar && !isNativeImage) {
            val dynamicOutputDir = Path.of("target/jte-dynamic")
            // Auto-clean stale compiled templates on startup
            if (dynamicOutputDir.toFile().exists()) {
                dynamicOutputDir.toFile().deleteRecursively()
            }
            if (!dynamicOutputDir.toFile().mkdirs() && !dynamicOutputDir.toFile().exists()) {
                logger.warn("Could not create JTE dynamic output directory: $dynamicOutputDir")
            }
            logger.info("Using dynamic JTE engine (live-reload from src/main/jte/)")
            TemplateEngine.create(
                DirectoryCodeResolver(sourceDir),
                dynamicOutputDir,
                ContentType.Html,
                javaClass.classLoader,
            )
        } else {
            logger.info("Using precompiled JTE engine")
            TemplateEngine.createPrecompiled(ContentType.Html)
        }
    }

    fun render(
        template: String,
        model: Map<String, Any?>,
    ): String {
        val output = StringOutput()
        engine.render(template, model, output)
        return output.toString()
    }
}

// Keep backward compatibility for tests that use TemplateEngine directly
object TemplateEngine {
    private val renderer = TemplateRenderer()

    fun render(
        template: String,
        model: Map<String, Any?>,
    ): String = renderer.render(template, model)
}
