Args = \
  --no-fallback \
  -Djava.awt.headless=true \
  --initialize-at-build-time=org.slf4j \
  --initialize-at-build-time=ch.qos.logback \
  --initialize-at-build-time=kotlin.KotlinVersion \
  --enable-url-protocols=http,https \
  -march=compatibility \
  -H:+ReportExceptionStackTraces \
  -H:+AddAllCharsets
