CREATE TABLE user_permissions (
    user_id                    CHAR(36)  PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    can_manage_libraries       BOOLEAN   NOT NULL DEFAULT TRUE,
    can_upload_books           BOOLEAN   NOT NULL DEFAULT TRUE,
    can_download_books         BOOLEAN   NOT NULL DEFAULT TRUE,
    can_delete_books           BOOLEAN   NOT NULL DEFAULT FALSE,
    can_edit_metadata          BOOLEAN   NOT NULL DEFAULT TRUE,
    can_manage_bookmarks       BOOLEAN   NOT NULL DEFAULT TRUE,
    can_manage_annotations     BOOLEAN   NOT NULL DEFAULT TRUE,
    can_manage_reading_progress BOOLEAN  NOT NULL DEFAULT TRUE,
    can_manage_shelves         BOOLEAN   NOT NULL DEFAULT TRUE,
    can_export_books           BOOLEAN   NOT NULL DEFAULT TRUE,
    can_send_to_device         BOOLEAN   NOT NULL DEFAULT TRUE,
    can_use_kobo_sync          BOOLEAN   NOT NULL DEFAULT TRUE,
    can_use_koreader_sync      BOOLEAN   NOT NULL DEFAULT TRUE,
    can_use_opds               BOOLEAN   NOT NULL DEFAULT TRUE,
    can_use_api_tokens         BOOLEAN   NOT NULL DEFAULT TRUE,
    can_manage_journal         BOOLEAN   NOT NULL DEFAULT TRUE,
    can_manage_reading_sessions BOOLEAN  NOT NULL DEFAULT TRUE,
    can_view_stats             BOOLEAN   NOT NULL DEFAULT TRUE,
    can_edit_profile           BOOLEAN   NOT NULL DEFAULT TRUE,
    can_change_password        BOOLEAN   NOT NULL DEFAULT TRUE,
    can_change_email           BOOLEAN   NOT NULL DEFAULT TRUE,
    can_use_search_filters     BOOLEAN   NOT NULL DEFAULT TRUE,
    can_view_audit_log         BOOLEAN   NOT NULL DEFAULT FALSE,
    can_access_komga_api       BOOLEAN   NOT NULL DEFAULT TRUE,
    can_manage_notebooks       BOOLEAN   NOT NULL DEFAULT TRUE,
    can_manage_fonts           BOOLEAN   NOT NULL DEFAULT TRUE,
    can_access_admin_panel     BOOLEAN   NOT NULL DEFAULT FALSE,
    updated_at                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
